[2020-03-04 08:45:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost:8888/Symfony2.0/")" at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://localhost:8888/Symfony2.0/\") at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-04 08:49:31] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost:8888/Symfony2.0/")" at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://localhost:8888/Symfony2.0/\") at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-04 08:52:10] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-04 08:52:10] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"21f479"},"request_uri":"http://localhost:8000/_wdt/21f479","method":"GET"} []
[2020-03-04 09:58:45] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost:8888/Symfony2.0/")" at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://localhost:8888/Symfony2.0/\") at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-04 09:59:59] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 09:59:59] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:04:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost:8888/Symfony2.0/")" at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://localhost:8888/Symfony2.0/\") at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-04 10:04:39] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:04:39] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:07:03] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:07:03] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:09:01] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:09:01] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:10:40] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:10:40] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:14:03] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:14:03] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:14:44] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:14:44] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:19:13] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:19:13] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:25:54] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:25:54] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:26:22] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:26:22] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:27:57] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:27:57] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:29:08] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:29:08] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:29:32] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:29:32] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:39:09] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:39:09] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:41:05] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:41:05] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:48:31] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:48:31] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:49:39] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:49:39] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:50:24] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:50:24] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:57:36] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2020-03-04 10:57:36] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 10:58:50] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)"} []
[2020-03-04 10:58:50] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2020-03-04 11:09:55] console.ERROR: Error thrown while running command "'make:'". Message: "Command "make:" is ambiguous. Did you mean one of these?     make:auth                  Creates a Guard authenticator of different flavors     make:command               Creates a new console command class     make:controller            Creates a new controller class     make:crud                  Creates CRUD for Doctrine entity class     make:entity                Creates or updates a Doctrine entity class, and optionally an API Platform resource     make:fixtures              Creates a new class to load Doctrine fixtures     make:form                  Creates a new form class     make:functional-test       Creates a new functional test class     make:registration-form     Creates a new registration form system     make:serializer:encoder    Creates a new serializer encoder class     make:serializer:normalizer Creates a new serializer normalizer class     make:subscriber            Creates a new event subscriber class     make:twig-extension        Creates a new Twig extension class     make:unit-test             Creates a new unit test class     make:validator             Creates a new validator and constraint class     make:voter                 Creates a new security voter class     make:user                  Creates a new security user class     make:migration             Creates a new migration based on database changes" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"make:\" is ambiguous.\nDid you mean one of these?\n    make:auth                  Creates a Guard authenticator of different flavors\n    make:command               Creates a new console command class\n    make:controller            Creates a new controller class\n    make:crud                  Creates CRUD for Doctrine entity class\n    make:entity                Creates or updates a Doctrine entity class, and optionally an API Platform resource\n    make:fixtures              Creates a new class to load Doctrine fixtures\n    make:form                  Creates a new form class\n    make:functional-test       Creates a new functional test class\n    make:registration-form     Creates a new registration form system\n    make:serializer:encoder    Creates a new serializer encoder class\n    make:serializer:normalizer Creates a new serializer normalizer class\n    make:subscriber            Creates a new event subscriber class\n    make:twig-extension        Creates a new Twig extension class\n    make:unit-test             Creates a new unit test class\n    make:validator             Creates a new validator and constraint class\n    make:voter                 Creates a new security voter class\n    make:user                  Creates a new security user class\n    make:migration             Creates a new migration based on database changes at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/console/Application.php:710)","command":"'make:'","message":"Command \"make:\" is ambiguous.\nDid you mean one of these?\n    make:auth                  Creates a Guard authenticator of different flavors\n    make:command               Creates a new console command class\n    make:controller            Creates a new controller class\n    make:crud                  Creates CRUD for Doctrine entity class\n    make:entity                Creates or updates a Doctrine entity class, and optionally an API Platform resource\n    make:fixtures              Creates a new class to load Doctrine fixtures\n    make:form                  Creates a new form class\n    make:functional-test       Creates a new functional test class\n    make:registration-form     Creates a new registration form system\n    make:serializer:encoder    Creates a new serializer encoder class\n    make:serializer:normalizer Creates a new serializer normalizer class\n    make:subscriber            Creates a new event subscriber class\n    make:twig-extension        Creates a new Twig extension class\n    make:unit-test             Creates a new unit test class\n    make:validator             Creates a new validator and constraint class\n    make:voter                 Creates a new security voter class\n    make:user                  Creates a new security user class\n    make:migration             Creates a new migration based on database changes"} []
[2020-03-04 11:12:15] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost:8888/Symfony2.0/")" at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://localhost:8888/Symfony2.0/\") at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-04 11:13:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "http://localhost:8888/Symfony2.0/")" at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"http://localhost:8888/Symfony2.0/\") at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-04 11:15:50] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://localhost:8000/register","method":"GET"} []
[2020-03-04 11:15:50] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-03-04 11:15:50] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"28af6f"},"request_uri":"http://localhost:8000/_wdt/28af6f","method":"GET"} []
[2020-03-04 11:16:18] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://localhost:8000/register","method":"POST"} []
[2020-03-04 11:16:18] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-03-04 11:16:18] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.email = ? ["kevin@mathe.fr"] []
[2020-03-04 11:16:18] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.email = ?' with params ["kevin@mathe.fr"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.user' doesn't exist" at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 42 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.email = ?' with params [\"kevin@mathe.fr\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.user' doesn't exist at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:42, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.user' doesn't exist at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_name.user' doesn't exist at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} []
[2020-03-04 11:16:19] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"9be7f1"},"request_uri":"http://localhost:8000/_wdt/9be7f1","method":"GET"} []
[2020-03-04 11:31:32] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-03-04 11:31:32] doctrine.DEBUG: CREATE TABLE migration_versions (version VARCHAR(14) NOT NULL, executed_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB [] []
[2020-03-04 11:31:32] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-03-04 11:31:32] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'db_name' AND TABLE_NAME = 'migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2020-03-04 11:31:32] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'migration_versions' */ WHERE k.table_name = 'migration_versions' AND k.table_schema = 'db_name' /*!50116 AND c.constraint_schema = 'db_name' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-03-04 11:31:32] doctrine.DEBUG: SELECT TABLE_NAME AS `Table`, NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, SEQ_IN_INDEX AS Seq_in_index, COLUMN_NAME AS Column_Name, COLLATION AS Collation, CARDINALITY AS Cardinality, SUB_PART AS Sub_Part, PACKED AS Packed, NULLABLE AS `Null`, INDEX_TYPE AS Index_Type, COMMENT AS Comment FROM information_schema.STATISTICS WHERE TABLE_NAME = 'migration_versions' AND TABLE_SCHEMA = 'db_name' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-03-04 11:31:32] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'migration_versions' [] []
[2020-03-04 11:31:48] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-03-04 11:31:48] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'db_name' AND TABLE_NAME = 'migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2020-03-04 11:31:48] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'migration_versions' */ WHERE k.table_name = 'migration_versions' AND k.table_schema = 'db_name' /*!50116 AND c.constraint_schema = 'db_name' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-03-04 11:31:48] doctrine.DEBUG: SELECT TABLE_NAME AS `Table`, NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, SEQ_IN_INDEX AS Seq_in_index, COLUMN_NAME AS Column_Name, COLLATION AS Collation, CARDINALITY AS Cardinality, SUB_PART AS Sub_Part, PACKED AS Packed, NULLABLE AS `Null`, INDEX_TYPE AS Index_Type, COMMENT AS Comment FROM information_schema.STATISTICS WHERE TABLE_NAME = 'migration_versions' AND TABLE_SCHEMA = 'db_name' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-03-04 11:31:48] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'migration_versions' [] []
[2020-03-04 11:31:48] doctrine.DEBUG: SELECT version FROM migration_versions [] []
[2020-03-04 11:31:52] doctrine.DEBUG: SELECT version FROM migration_versions WHERE version IN ('20200304113132') ORDER BY version DESC LIMIT 1 [] []
[2020-03-04 11:31:52] doctrine.DEBUG: SELECT version FROM migration_versions [] []
[2020-03-04 11:31:52] doctrine.DEBUG: "START TRANSACTION" [] []
[2020-03-04 11:31:52] doctrine.DEBUG: CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB [] []
[2020-03-04 11:31:52] doctrine.DEBUG: INSERT INTO migration_versions (version, executed_at) VALUES (?, ?) ["20200304113132","2020-03-04 11:31:52"] []
[2020-03-04 11:31:52] doctrine.DEBUG: "COMMIT" [] []
[2020-03-04 11:32:28] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://localhost:8000/register","method":"GET"} []
[2020-03-04 11:32:28] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-03-04 11:32:28] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-04 11:32:28] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-04 11:32:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-03-04 11:32:28] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"0f0857"},"request_uri":"http://localhost:8000/_wdt/0f0857","method":"GET"} []
[2020-03-04 11:32:37] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://localhost:8000/register","method":"POST"} []
[2020-03-04 11:32:37] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-03-04 11:32:37] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-04 11:32:37] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-04 11:32:37] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-03-04 11:32:37] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.email = ? ["kevin@mathe.fr"] []
[2020-03-04 11:32:37] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"574589"},"request_uri":"http://localhost:8000/_wdt/574589","method":"GET"} []
[2020-03-04 11:32:45] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://localhost:8000/register","method":"POST"} []
[2020-03-04 11:32:45] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-03-04 11:32:45] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-04 11:32:45] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-04 11:32:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-03-04 11:32:45] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.email = ? ["kevin@mathe.fr"] []
[2020-03-04 11:32:45] doctrine.DEBUG: "START TRANSACTION" [] []
[2020-03-04 11:32:45] doctrine.DEBUG: INSERT INTO user (email, roles, password) VALUES (?, ?, ?) {"1":"kevin@mathe.fr","2":[],"3":"$2y$13$dp30eZ5YVs.kt8o9gVp [...]"} []
[2020-03-04 11:32:45] doctrine.DEBUG: "COMMIT" [] []
[2020-03-04 11:32:45] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "" as such route does not exist." at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Generator/CompiledUrlGenerator.php line 50 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"\" as such route does not exist. at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"} []
[2020-03-04 11:32:45] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"820810"},"request_uri":"http://localhost:8000/_wdt/820810","method":"GET"} []
[2020-03-04 12:48:13] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://localhost:8000/register","method":"POST"} []
[2020-03-04 12:48:13] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-03-04 12:48:13] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-04 12:48:13] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-04 12:48:13] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-03-04 12:48:13] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.email = ? ["kevin@mathe.fr"] []
[2020-03-04 12:48:13] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ad8ab2"},"request_uri":"http://localhost:8000/_wdt/ad8ab2","method":"GET"} []
[2020-03-06 07:55:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-03-06 07:55:30] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"86147b"},"request_uri":"http://localhost:8000/_wdt/86147b","method":"GET"} []
[2020-03-06 07:55:31] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico"" at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/http-kernel/EventListener/RouterListener.php:136, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2020-03-06 07:55:39] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://localhost:8000/register","method":"GET"} []
[2020-03-06 07:55:39] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-03-06 07:55:39] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-06 07:55:39] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-06 07:55:40] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-03-06 07:55:40] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ee63a2"},"request_uri":"http://localhost:8000/_wdt/ee63a2","method":"GET"} []
[2020-03-06 07:55:58] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://localhost:8000/register","method":"POST"} []
[2020-03-06 07:55:58] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-03-06 07:55:58] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-06 07:55:58] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-06 07:55:58] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-03-06 07:55:58] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 93 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Applications/MAMP/htdocs/Symfony2.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)"} []
[2020-03-06 07:55:59] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d00953"},"request_uri":"http://localhost:8000/_wdt/d00953","method":"GET"} []
[2020-03-06 07:57:00] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://localhost:8000/register","method":"POST"} []
[2020-03-06 07:57:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-03-06 07:57:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-06 07:57:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-06 07:57:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-03-06 07:57:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.email = ? ["aliore@mail.fr"] []
[2020-03-06 07:57:01] doctrine.DEBUG: "START TRANSACTION" [] []
[2020-03-06 07:57:01] doctrine.DEBUG: INSERT INTO user (email, roles, password) VALUES (?, ?, ?) {"1":"aliore@mail.fr","2":[],"3":"$2y$13$mg4BiKSWJU8mqbZzO.B [...]"} []
[2020-03-06 07:57:01] doctrine.DEBUG: "COMMIT" [] []
[2020-03-06 07:57:01] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "" as such route does not exist." at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Generator/CompiledUrlGenerator.php line 50 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"\" as such route does not exist. at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"} []
[2020-03-06 07:57:01] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"8f9956"},"request_uri":"http://localhost:8000/_wdt/8f9956","method":"GET"} []
[2020-03-06 08:03:58] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://localhost:8000/register","method":"POST"} []
[2020-03-06 08:03:58] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2020-03-06 08:03:58] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-06 08:03:58] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2020-03-06 08:03:58] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-03-06 08:03:58] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.email = ? ["salah@mail.fr"] []
[2020-03-06 08:03:58] doctrine.DEBUG: "START TRANSACTION" [] []
[2020-03-06 08:03:58] doctrine.DEBUG: INSERT INTO user (email, roles, password) VALUES (?, ?, ?) {"1":"salah@mail.fr","2":[],"3":"$2y$13$2QfdSLpC6TM1zjCRfgs [...]"} []
[2020-03-06 08:03:58] doctrine.DEBUG: "COMMIT" [] []
[2020-03-06 08:03:58] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "/" as such route does not exist." at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Generator/CompiledUrlGenerator.php line 50 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"/\" as such route does not exist. at /Applications/MAMP/htdocs/Symfony2.0/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"} []
[2020-03-06 08:03:58] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"9a4053"},"request_uri":"http://localhost:8000/_wdt/9a4053","method":"GET"} []
